num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("Addition=",num1 + num2)
print("Subtraction=",num1 - num2)
print("Multiplpication=",num1 * num2)
print("Division=",num1 / num2)
print("Floor division=",num1 // num2)
print("Modulus=", num1 % num2)
print("Exponentional=", num1 ** num2)